# LUKS Encryption Configuration (samuels-terra)
#
# Encrypted devices:
# - cryptroot: Main system partition (root, home, nix, persist)
#
# Unlock method:
#   features.encryption.unlockMethod = "yubikey"  → fido2-device=auto (YubiKey FIDO2 touch at boot)
#   features.encryption.unlockMethod = "tpm2"     → tpm2-device=auto  (TPM2 auto-unlock, default)
#   features.encryption.unlockMethod = "password" → prompt for LUKS passphrase
#
# Setup:
#   YubiKey: yubikey-luks-init
#   TPM2:    tpm-luks-init
#
# Partition labels:
# - Generated by disko as: disk-<diskname>-<partitionname>
# - cryptroot: disk-main-root

{ config, ... }:

let
  unlockOpts = {
    yubikey = [ "fido2-device=auto" ];
    tpm2 = [ "tpm2-device=auto" ];
    password = [ ];
  };
in
{
  boot.initrd.luks.devices = {
    "cryptroot" = {
      device = "/dev/disk/by-partlabel/disk-main-root";
      allowDiscards = true;
      crypttabExtraOpts = unlockOpts.${config.features.encryption.unlockMethod};
    };
  };

  # cryptroot failing → reboot (system can't boot without it)
  boot.initrd.systemd.services."systemd-cryptsetup@cryptroot" = {
    overrideStrategy = "asDropin";
    unitConfig.FailureAction = "reboot-force";
  };
}
