# LUKS Encryption Configuration (samuels-terra)
#
# Encrypted devices:
# - cryptroot: Main system partition (root, home, nix, persist)
#
# Unlock method:
#   features.encryption.unlockMethod = "yubikey"  → FIDO2 touch at boot
#   features.encryption.unlockMethod = "tpm2"     → TPM2 auto-unlock
#   features.encryption.unlockMethod = "password" → LUKS passphrase prompt
#
# Setup:
#   YubiKey: yubikey-luks-init
#   TPM2:    tpm-luks-init
#
# Partition labels:
# - Generated by disko as: disk-<diskname>-<partitionname>
# - cryptroot: disk-main-root

{ config, ... }:

let
  unlockOpts = {
    yubikey = [ "fido2-device=auto" "tries=0" ];
    tpm2    = [ "tpm2-device=auto"  "tries=0" ];
    password = [ "tries=0" ];
  };
in
{
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-partlabel/disk-main-root";
    allowDiscards = true;
    crypttabExtraOpts = unlockOpts.${config.features.encryption.unlockMethod};
  };

  # On FIDO2 timeout/failure: fall back to password prompt instead of rebooting.
  boot.initrd.systemd.services."systemd-cryptsetup@cryptroot" = {
    overrideStrategy = "asDropin";
    unitConfig.FailureAction = "none";
  };
}
