# LUKS Encryption Configuration (samuels-terra)
#
# Encrypted devices:
# - cryptroot: Main system partition (root, home, nix, persist)
#
# Unlock method:
#   features.encryption.unlockMethod = "yubikey"  → fido2-device=auto (YubiKey FIDO2 touch at boot)
#   features.encryption.unlockMethod = "tpm2"     → tpm2-device=auto  (TPM2 auto-unlock, default)
#   features.encryption.unlockMethod = "password" → prompt for LUKS passphrase
#
# Setup:
#   YubiKey: yubikey-luks-init
#   TPM2:    tpm-luks-init
#
# Partition labels:
# - Generated by disko as: disk-<diskname>-<partitionname>
# - cryptroot: disk-main-root

{ config, lib, ... }:

let
  method = config.features.encryption.unlockMethod;
in
{
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-partlabel/disk-main-root";
    allowDiscards = true;
    # tries=0: unlimited password attempts
    crypttabExtraOpts = [ "tries=0" ];
  };

  # systemd-cryptsetup in the initrd reads unlock options from here, not crypttabExtraOpts
  boot.initrd.systemd.luks.devices."cryptroot" = lib.mkMerge [
    (lib.mkIf (method == "yubikey") {
      fido2 = {
        enable = true;
        device = "auto";
        credential = "auto";
      };
    })
    (lib.mkIf (method == "tpm2") {
      tpm2.enable = true;
    })
  ];

  # On FIDO2 timeout/failure: fall back to password prompt instead of rebooting.
  boot.initrd.systemd.services."systemd-cryptsetup@cryptroot" = {
    overrideStrategy = "asDropin";
    unitConfig.FailureAction = "none";
  };
}
