# LUKS configuration with TPM2 auto-unlock
# Partlabels are generated by disko as: disk-<diskname>-<partitionname>
# Keys are enrolled with: systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7
{ ... }:

{
  boot.initrd.luks.devices = {
    "cryptroot" = {
      device = "/dev/disk/by-partlabel/disk-main-root";
      allowDiscards = true;
      crypttabExtraOpts = [ "tpm2-device=auto" ];
    };
  };
}
