# Desktop Theme Configuration (Common)
#
# This module configures core theming shared across all window managers:
# - GTK theme (Catppuccin)
# - Icon and cursor themes
# - Catppuccin flavor/accent
# - Electron Wayland support
#
# WM-specific theming:
# - Hyprland: See hyprland/theme.nix (Qt/Kvantum, hidden window buttons)
# - KDE: See kde/theme.nix (Plasma integration, window decorations)

{
  config,
  pkgs,
  lib,
  fonts,
  theme,
  ...
}:

let
  # Theme colors and packages
  inherit (theme.catppuccin) flavor accent;
  isLight = flavor == "latte";

  # Catppuccin palette loaded once, shared across modules
  palette = (lib.importJSON "${config.catppuccin.sources.palette}/palette.json").${flavor}.colors;
  iconName = theme.icons.name;
  iconPackage = theme.icons.package;
  cursorName = theme.cursor.name;
  cursorPackage = theme.cursor.package;
  cursorSize = theme.cursor.size;

  # GTK theme (used by all WMs)
  catppuccinGtk = pkgs.catppuccin-gtk.override {
    accents = [ accent ];
    variant = flavor;
  };
  themeName = "catppuccin-${flavor}-${accent}-standard";

in
{
  #===========================
  # Options
  #===========================

  options = {
    theme.catppuccinPalette = lib.mkOption {
      type = lib.types.attrs;
      readOnly = true;
      default = palette;
      internal = true;
    };

    theme.catppuccin.restartTrigger = lib.mkOption {
      type = lib.types.path;
      readOnly = true;
      default = pkgs.writeText "catppuccin-theme" ''
        ${flavor}
        ${accent}
      '';
      internal = true;
    };
  };

  #===========================
  # Configuration
  #===========================

  config = {
    #---------------------------
    # Generic Theme
    #---------------------------
    # GTK, cursor, catppuccin, session variables

    xdg = {
      # GTK4 ignores the theme package — it loads CSS from ~/.config/gtk-4.0/ directly.
      # These files are generated theme artifacts. The Flatpak activation below
      # turns them into real files, so Home Manager must reclaim them on updates.
      configFile."gtk-4.0/gtk.css" = {
        source = "${catppuccinGtk}/share/themes/${themeName}/gtk-4.0/gtk.css";
        force = true;
      };
      configFile."gtk-4.0/gtk-dark.css" = {
        source = "${catppuccinGtk}/share/themes/${themeName}/gtk-4.0/gtk-dark.css";
        force = true;
      };
    };

    # GTK2 does not consume the GTK3/GTK4 settings generated by the Home
    # Manager GTK module. Keep legacy applications aligned with the same
    # theme, icons, font, and cursor configuration.
    xdg.configFile.".gtkrc-2.0".text = ''
      gtk-theme-name = "${themeName}"
      gtk-icon-theme-name = "${iconName}"
      gtk-font-name = "${fonts.ui} ${toString fonts.size}"
      gtk-cursor-theme-name = "${cursorName}"
      gtk-cursor-theme-size = ${toString cursorSize}
    '';

    home = {
      pointerCursor = {
        enable = true;
        name = cursorName;
        package = cursorPackage;
        size = cursorSize;
        gtk.enable = true;
        x11.enable = true;
      };

      # Make GTK theme available to Flatpak apps
      # Flatpak sandbox can't follow symlinks to the Nix store.
      # Replace theme dir symlink AND gtk-4.0 CSS symlinks with real files.
      activation.copyGtkThemeForFlatpak = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        THEME_DIR="$HOME/.local/share/themes/${themeName}"
        SOURCE_DIR="${catppuccinGtk}/share/themes/${themeName}"
        GTK4_DIR="$HOME/.config/gtk-4.0"
        ICON_DIR="$HOME/.local/share/icons/${iconName}"
        ICON_SOURCE_DIR="${iconPackage}/share/icons/${iconName}"

        if [ -d "$SOURCE_DIR" ]; then
           [ -e "$THEME_DIR" ] && ${pkgs.coreutils}/bin/chmod -R u+w "$THEME_DIR" 2>/dev/null || true
           ${pkgs.coreutils}/bin/rm -rf "$THEME_DIR"
           ${pkgs.coreutils}/bin/mkdir -p "$(${pkgs.coreutils}/bin/dirname "$THEME_DIR")"
           ${pkgs.coreutils}/bin/cp -rL --reflink=auto "$SOURCE_DIR" "$THEME_DIR"
        fi

        # Replace gtk-4.0 CSS symlinks with real files (flatpak can't follow Nix store symlinks)
        for css in gtk.css gtk-dark.css; do
          CSS_FILE="$GTK4_DIR/$css"
          if [ -L "$CSS_FILE" ]; then
             CONTENT=$(${pkgs.coreutils}/bin/cat "$CSS_FILE" 2>/dev/null)
            if [ -n "$CONTENT" ]; then
               ${pkgs.coreutils}/bin/rm -f "$CSS_FILE"
              printf '%s\n' "$CONTENT" > "$CSS_FILE"
            fi
          fi
        done

        # Flatpak cannot follow the icon theme symlink into the Nix store.
        if [ -d "$ICON_SOURCE_DIR" ]; then
           [ -e "$ICON_DIR" ] && ${pkgs.coreutils}/bin/chmod -R u+w "$ICON_DIR" 2>/dev/null || true
           ${pkgs.coreutils}/bin/rm -rf "$ICON_DIR"
           ${pkgs.coreutils}/bin/mkdir -p "$(${pkgs.coreutils}/bin/dirname "$ICON_DIR")"
           ${pkgs.coreutils}/bin/cp -rL --reflink=auto "$ICON_SOURCE_DIR" "$ICON_DIR"
        fi
      '';

    };

    gtk = {
      enable = true;
      font = {
        inherit (fonts) size;
        name = fonts.ui;
      };
      theme = {
        name = themeName;
        package = catppuccinGtk;
      };
      iconTheme = {
        name = lib.mkForce iconName;
        package = lib.mkForce iconPackage;
      };
      # WebKitGTK/Tauri apps need this to detect dark mode
      gtk3.extraConfig.gtk-application-prefer-dark-theme = !isLight;
      gtk4 = {
        extraConfig.gtk-application-prefer-dark-theme = !isLight;
        theme = null;
      };
    };

    dconf.settings."org/gnome/desktop/interface".color-scheme =
      if isLight then "prefer-light" else "prefer-dark";
  };
}
