# LUKS Encryption Configuration (samuels-pc)
#
# Encrypted devices:
# - cryptroot: Main system partition (root, home, nix, persist)
# - cryptgames: Games partition (Steam library)
#
# Unlock method:
#   features.encryption.unlockMethod = "yubikey"  → FIDO2 touch at boot
#   features.encryption.unlockMethod = "tpm2"     → TPM2 auto-unlock
#   features.encryption.unlockMethod = "password" → LUKS passphrase prompt
#
# Setup:
#   YubiKey: yubikey-luks-init
#   TPM2:    tpm-luks-init
#
# Partition labels:
# - Generated by disko as: disk-<diskname>-<partitionname>
# - cryptroot: disk-main-root
# - cryptgames: disk-games-games

{ config, ... }:

let
  unlockOpts = {
    yubikey = [ "fido2-device=auto" "token-timeout=10s" ];
    tpm2    = [ "tpm2-device=auto" ];
    password = [ ];
  };
in
{
  boot.initrd.luks.devices = {
    "cryptroot" = {
      device = "/dev/disk/by-partlabel/disk-main-root";
      allowDiscards = true;
      crypttabExtraOpts = unlockOpts.${config.features.encryption.unlockMethod};
    };
    "cryptgames" = {
      device = "/dev/disk/by-partlabel/disk-games-games";
      allowDiscards = true;
      crypttabExtraOpts = unlockOpts.${config.features.encryption.unlockMethod};
    };
  };

  # Do not reboot the machine when FIDO2 unlock fails or times out.
  boot.initrd.systemd.services."systemd-cryptsetup@cryptroot" = {
    overrideStrategy = "asDropin";
    unitConfig.FailureAction = "none";
  };
}
