# LUKS Encryption Configuration (samuels-pc)
#
# Encrypted devices:
# - cryptroot: Main system partition (root, home, nix, persist)
# - cryptgames: Games partition (Steam library)
#
# Unlock method:
#   features.encryption.unlockMethod = "yubikey"  → fido2-device=auto (YubiKey FIDO2 touch at boot)
#   features.encryption.unlockMethod = "tpm2"     → tpm2-device=auto  (TPM2 auto-unlock, default)
#   features.encryption.unlockMethod = "password" → prompt for LUKS passphrase
#
# Setup:
#   YubiKey: yubikey-luks-init
#   TPM2:    tpm-luks-init
#
# Partition labels:
# - Generated by disko as: disk-<diskname>-<partitionname>
# - cryptroot: disk-main-root
# - cryptgames: disk-games-games

{ config, ... }:

let
  unlockOpts = {
    yubikey = [ "fido2-device=auto" "fido2-no-client-pin" "tries=0" ];
    tpm2 = [ "tpm2-device=auto" "tries=0" ];
    password = [ "tries=0" ];
  };
in
{
  boot.initrd.luks.devices = {
    "cryptroot" = {
      device = "/dev/disk/by-partlabel/disk-main-root";
      allowDiscards = true;
      crypttabExtraOpts = unlockOpts.${config.features.encryption.unlockMethod};
    };
    "cryptgames" = {
      device = "/dev/disk/by-partlabel/disk-games-games";
      allowDiscards = true;
      crypttabExtraOpts = unlockOpts.${config.features.encryption.unlockMethod};
    };
  };

  # On FIDO2 timeout/failure: fall back to password prompt instead of rebooting.
  # reboot-force would cause an endless loop if the YubiKey is not detected.
  boot.initrd.systemd.services."systemd-cryptsetup@cryptroot" = {
    overrideStrategy = "asDropin";
    unitConfig.FailureAction = "none";
  };
}
